LootJS.modifiers(e => {
    e.addEntityLootModifier("alexscaves:forsaken")
    .addLoot("rimcraft:devil_eye")
    e.addEntityLootModifier("alexscaves:licowitch")
    .removeLoot('alexscaves:vanilla_ice_cream_scoop')
    .removeLoot('alexscaves:chocolate_ice_cream_scoop')
    .removeLoot('alexscaves:sweetberry_ice_cream_scoop')
    .addWeightedLoot([0, 1], [Item.of('rimcraftcore:strawberry_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('rimcraftcore:banana_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('rimcraftcore:mint_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('rimcraftcore:adzuki_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('rimcraftcore:pomegranate_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('rimcraftcore:lime_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('alexscaves:vanilla_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('alexscaves:chocolate_ice_cream_scoop').withChance(0.33)])
    .addWeightedLoot([0, 1], [Item.of('alexscaves:sweetberry_ice_cream_scoop').withChance(0.33)])
})