ServerEvents.recipes(e => {
    e.recipes.kubejs.shapeless("rimcraftcore:tin_block", "9x rimcraftcore:tin_ingot")
    .id("rimcraftcore:tin_block_from_tin_ingot")
    e.recipes.kubejs.shapeless("9x rimcraftcore:tin_ingot", "rimcraftcore:tin_block")
    .id("rimcraftcore:tin_ingot_from_tin_block")
    e.recipes.kubejs.shapeless("9x rimcraftcore:tin_nugget", "rimcraftcore:tin_ingot")
    .id("rimcraftcore:tin_nugget_from_tin_ingot")
    e.recipes.kubejs.shapeless("rimcraftcore:tin_ingot", "9x rimcraftcore:tin_nugget")
    .id("rimcraftcore:tin_ingot_from_tin_nugget")
    e.recipes.kubejs.shapeless("rimcraftcore:raw_tin_block", "9x rimcraftcore:raw_tin")
    .id("rimcraftcore:raw_tin_block_from_raw_tin")
    e.recipes.kubejs.shapeless("9x rimcraftcore:raw_tin", "rimcraftcore:raw_tin_block")
    .id("rimcraftcore:raw_tin_from_raw_tin_block")
    e.recipes.minecraft.blasting("rimcraftcore:tin_ingot", "rimcraftcore:raw_tin")
    e.recipes.minecraft.smelting("rimcraftcore:tin_ingot", "rimcraftcore:raw_tin")
    e.recipes.minecraft.blasting("rimcraftcore:tin_block", "rimcraftcore:raw_tin_block")
    e.recipes.minecraft.smelting("rimcraftcore:tin_block", "rimcraftcore:raw_tin_block")
})