ServerEvents.recipes(e => {
    const {create, createmetallurgy, vintageimprovements} = e.recipes
    create.compacting("ratatouille:sausage_casing", Fluid.of("rimcraftcore:slime", 30))
    .id("rimcraft:compacting/sausage_casing")
    create.compacting("minecraft:slime_block", Fluid.of("rimcraftcore:slime", 810))
    .id("rimcraft:compacting/slime_block")
    create.compacting("minecraft:slime_ball", Fluid.of("rimcraftcore:slime", 90))
    .id("rimcraft:compacting/slime_ball")
    create.mixing(Fluid.of("rimcraftcore:slime", 90), "minecraft:slime_ball")
    .heated()
    .id("rimcraft:mixing/slime_fluid_1")
    create.mixing(Fluid.of("rimcraftcore:slime", 810), "minecraft:slime_block")
    .heated()
    .id("rimcraft:mixing/slime_fluid_2")
    create.filling("create:super_glue", ["create:iron_sheet", Fluid.of("rimcraftcore:slime", 90)])
    .id("rimcraft:filling/super_glue")
    vintageimprovements.pressurizing(Fluid.of("rimcraftcore:slime", 30), "minecraft:kelp")
    .heated()
    .id("rimcraft:pressurizing/slime_fluid")
})